# Generated by Django 6.0.5 on 2026-05-05 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id_dogovora', models.AutoField(primary_key=True, serialize=False, verbose_name='ID договора')),
                ('nomer_dogovora', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('metrika_sroka', models.DateField(blank=True, null=True, verbose_name='Метрика срока')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='GruppaIspolnitelei',
            fields=[
                ('id_gruppy', models.AutoField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('naimenovanie_gruppy', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа исполнителей',
                'verbose_name_plural': 'Группы исполнителей',
            },
        ),
        migrations.CreateModel(
            name='StatusZayavki',
            fields=[
                ('id_statusa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID статуса')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.CreateModel(
            name='Ispolnitel',
            fields=[
                ('id_ispolnitelya', models.AutoField(primary_key=True, serialize=False, verbose_name='ID исполнителя')),
                ('familia', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('aktiven_ili_net', models.BooleanField(default=True, verbose_name='Активен')),
                ('gruppa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gruppaispolnitelei', verbose_name='Группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Servisy',
            fields=[
                ('id_servisa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID сервиса')),
                ('naimenovanie', models.CharField(max_length=200, verbose_name='Наименование')),
                ('adress', models.TextField(blank=True, verbose_name='Адрес')),
                ('kontaktnyi_telefon', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('dogovor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dogovor', verbose_name='Договор')),
                ('gruppa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gruppaispolnitelei', verbose_name='Группа исполнителей')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Zayavki',
            fields=[
                ('id_zayavki', models.AutoField(primary_key=True, serialize=False, verbose_name='ID заявки')),
                ('data_sozdaniya_zayavki', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('naimenovanie', models.CharField(max_length=200, verbose_name='Название заявки')),
                ('srok_zayavki', models.DateField(blank=True, null=True, verbose_name='Срок заявки')),
                ('opisanie_problem', models.TextField(blank=True, verbose_name='Описание проблемы')),
                ('ispolnitel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ispolnitel', verbose_name='Исполнитель')),
                ('servis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servisy', verbose_name='Сервис')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.statuszayavki', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-data_sozdaniya_zayavki'],
            },
        ),
    ]
