# Generated by Django 6.0.5 on 2026-05-11 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servisy',
            name='dogovor',
        ),
        migrations.AlterModelOptions(
            name='zayavki',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='gruppaispolnitelei',
            name='id_gruppy',
        ),
        migrations.RemoveField(
            model_name='ispolnitel',
            name='id_ispolnitelya',
        ),
        migrations.RemoveField(
            model_name='servisy',
            name='gruppa',
        ),
        migrations.RemoveField(
            model_name='servisy',
            name='id_servisa',
        ),
        migrations.RemoveField(
            model_name='servisy',
            name='kontaktnyi_telefon',
        ),
        migrations.RemoveField(
            model_name='statuszayavki',
            name='id_statusa',
        ),
        migrations.RemoveField(
            model_name='zayavki',
            name='id_zayavki',
        ),
        migrations.AddField(
            model_name='gruppaispolnitelei',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ispolnitel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='servisy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='statuszayavki',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='zayavki',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gruppaispolnitelei',
            name='naimenovanie_gruppy',
            field=models.CharField(max_length=255, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='ispolnitel',
            name='familia',
            field=models.CharField(max_length=255, verbose_name='Фамилия Имя'),
        ),
        migrations.AlterField(
            model_name='servisy',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='servisy',
            name='naimenovanie',
            field=models.CharField(max_length=255, verbose_name='Название сервиса'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='naimenovanie',
            field=models.CharField(max_length=255, verbose_name='Название заявки'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='opisanie_problem',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='srok_zayavki',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.CreateModel(
            name='IstoriyaDeystviy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deystvie', models.CharField(max_length=255, verbose_name='Действие')),
                ('data_vremya', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('kto_izmenil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('zayavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zayavki', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История действий',
                'verbose_name_plural': 'История действий',
                'ordering': ['-data_vremya'],
            },
        ),
        migrations.DeleteModel(
            name='Dogovor',
        ),
    ]
