# Generated by Django 6.0.5 on 2026-05-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servisy_dogovor_alter_zayavki_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IstoriyaDeystviy',
        ),
    ]
