# Generated by Django 6.0.5 on 2026-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_istoriyadeystviy'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='priority',
            field=models.CharField(choices=[('high', '🔴 Высокий'), ('medium', '🟡 Средний'), ('low', '🟢 Низкий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
    ]
