# Generated by Django 6.0.5 on 2026-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_zayavki_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveZayavki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(blank=True, null=True, verbose_name='Оригинальный ID')),
                ('naimenovanie', models.CharField(max_length=255, verbose_name='Название заявки')),
                ('servis_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название сервиса')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус')),
                ('ispolnitel_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исполнитель')),
                ('data_sozdaniya_zayavki', models.DateTimeField(verbose_name='Дата создания')),
                ('data_udaleniya', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('srok_zayavki', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('opisanie_problem', models.TextField(verbose_name='Описание проблемы')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Удалил')),
            ],
            options={
                'verbose_name': 'Архивная заявка',
                'verbose_name_plural': 'Архив заявок',
                'ordering': ['-data_udaleniya'],
            },
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
    ]
