# Generated by Django 6.0.5 on 2026-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_archivezayavki_alter_zayavki_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchiveZayavki',
        ),
        migrations.AlterModelOptions(
            name='zayavki',
            options={'ordering': ['-data_sozdaniya_zayavki'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='zayavki',
            name='data_udaleniya',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='zayavki',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Удалил'),
        ),
        migrations.AddField(
            model_name='zayavki',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
    ]
