# Generated by Django 6.0.5 on 2026-06-10 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_archivezayavki_alter_zayavki_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavki',
            name='servis_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сервис/Оборудование'),
        ),
        migrations.AlterField(
            model_name='zayavki',
            name='servis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servisy', verbose_name='Сервис (старое)'),
        ),
    ]
